export const deckOfCards = [
  {
    id: 1,
    value: 11,
    suit: 'hearts',
    name: 'ace_of_hearts',
    isSelected: false,
  },
  {
    id: 2,
    value: 2,
    suit: 'hearts',
    name: '2_of_hearts',
    isSelected: false,
  },
  {
    id: 3,
    value: 3,
    suit: 'hearts',
    name: '3_of_hearts',
    isSelected: false,
  },
  {
    id: 4,
    value: 4,
    suit: 'hearts',
    name: '4_of_hearts',
    isSelected: false,
  },
  {
    id: 5,
    value: 5,
    suit: 'hearts',
    name: '5_of_hearts',
    isSelected: false,
  },
  {
    id: 6,
    value: 6,
    suit: 'hearts',
    name: '6_of_hearts',
    isSelected: false,
  },
  {
    id: 7,
    value: 7,
    suit: 'hearts',
    name: '7_of_hearts',
    isSelected: false,
  },
  {
    id: 8,
    value: 8,
    suit: 'hearts',
    name: '8_of_hearts',
    isSelected: false,
  },
  {
    id: 9,
    value: 9,
    suit: 'hearts',
    name: '9_of_hearts',
    isSelected: false,
  },
  {
    id: 10,
    value: 10,
    suit: 'hearts',
    name: '10_of_hearts',
    isSelected: false,
  },
  {
    id: 11,
    value: 10,
    suit: 'hearts',
    name: 'jack_of_hearts2',
    isSelected: false,
  },
  {
    id: 12,
    value: 10,
    suit: 'hearts',
    name: 'queen_of_hearts2',
    isSelected: false,
  },
  {
    id: 13,
    value: 10,
    suit: 'hearts',
    name: 'king_of_hearts2',
    isSelected: false,
  },
  {
    id: 14,
    value: 11,
    suit: 'diamonds',
    name: 'ace_of_diamonds',
    isSelected: false,
  },
  {
    id: 15,
    value: 2,
    suit: 'diamonds',
    name: '2_of_diamonds',
    isSelected: false,
  },
  {
    id: 16,
    value: 3,
    suit: 'diamonds',
    name: '3_of_diamonds',
    isSelected: false,
  },
  {
    id: 17,
    value: 4,
    suit: 'diamonds',
    name: '4_of_diamonds',
    isSelected: false,
  },
  {
    id: 18,
    value: 5,
    suit: 'diamonds',
    name: '5_of_diamonds',
    isSelected: false,
  },
  {
    id: 19,
    value: 6,
    suit: 'diamonds',
    name: '6_of_diamonds',
    isSelected: false,
  },
  {
    id: 20,
    value: 7,
    suit: 'diamonds',
    name: '7_of_diamonds',
    isSelected: false,
  },
  {
    id: 21,
    value: 8,
    suit: 'diamonds',
    name: '8_of_diamonds',
    isSelected: false,
  },
  {
    id: 22,
    value: 9,
    suit: 'diamonds',
    name: '9_of_diamonds',
    isSelected: false,
  },
  {
    id: 23,
    value: 10,
    suit: 'diamonds',
    name: '10_of_diamonds',
    isSelected: false,
  },
  {
    id: 24,
    value: 10,
    suit: 'diamonds',
    name: 'jack_of_diamonds2',
    isSelected: false,
  },
  {
    id: 25,
    value: 10,
    suit: 'diamonds',
    name: 'queen_of_diamonds2',
    isSelected: false,
  },
  {
    id: 26,
    value: 10,
    suit: 'diamonds',
    name: 'king_of_diamonds2',
    isSelected: false,
  },
  {
    id: 27,
    value: 11,
    suit: 'clubs',
    name: 'ace_of_clubs',
    isSelected: false,
  },
  {
    id: 28,
    value: 2,
    suit: 'clubs',
    name: '2_of_clubs',
    isSelected: false,
  },
  {
    id: 29,
    value: 3,
    suit: 'clubs',
    name: '3_of_clubs',
    isSelected: false,
  },
  {
    id: 30,
    value: 4,
    suit: 'clubs',
    name: '4_of_clubs',
    isSelected: false,
  },
  {
    id: 31,
    value: 5,
    suit: 'clubs',
    name: '5_of_clubs',
    isSelected: false,
  },
  {
    id: 32,
    value: 6,
    suit: 'clubs',
    name: '6_of_clubs',
    isSelected: false,
  },
  {
    id: 33,
    value: 7,
    suit: 'clubs',
    name: '7_of_clubs',
    isSelected: false,
  },
  {
    id: 34,
    value: 8,
    suit: 'clubs',
    name: '8_of_clubs',
    isSelected: false,
  },
  {
    id: 35,
    value: 9,
    suit: 'clubs',
    name: '9_of_clubs',
    isSelected: false,
  },
  {
    id: 36,
    value: 10,
    suit: 'clubs',
    name: '10_of_clubs',
    isSelected: false,
  },
  {
    id: 37,
    value: 10,
    suit: 'clubs',
    name: 'jack_of_clubs2',
    isSelected: false,
  },
  {
    id: 38,
    value: 10,
    suit: 'clubs',
    name: 'queen_of_clubs2',
    isSelected: false,
  },
  {
    id: 39,
    value: 10,
    suit: 'clubs',
    name: 'king_of_clubs2',
    isSelected: false,
  },
  {
    id: 40,
    value: 11,
    suit: 'spades',
    name: 'ace_of_spades',
    isSelected: false,
  },
  {
    id: 41,
    value: 2,
    suit: 'spades',
    name: '2_of_spades',
    isSelected: false,
  },
  {
    id: 42,
    value: 3,
    suit: 'spades',
    name: '3_of_spades',
    isSelected: false,
  },
  {
    id: 43,
    value: 4,
    suit: 'spades',
    name: '4_of_spades',
    isSelected: false,
  },
  {
    id: 44,
    value: 5,
    suit: 'spades',
    name: '5_of_spades',
    isSelected: false,
  },
  {
    id: 45,
    value: 6,
    suit: 'spades',
    name: '6_of_spades',
    isSelected: false,
  },
  {
    id: 46,
    value: 7,
    suit: 'spades',
    name: '7_of_spades',
    isSelected: false,
  },
  {
    id: 47,
    value: 8,
    suit: 'spades',
    name: '8_of_spades',
    isSelected: false,
  },
  {
    id: 48,
    value: 9,
    suit: 'spades',
    name: '9_of_spades',
    isSelected: false,
  },
  {
    id: 49,
    value: 10,
    suit: 'spades',
    name: '10_of_spades',
    isSelected: false,
  },
  {
    id: 50,
    value: 10,
    suit: 'spades',
    name: 'jack_of_spades2',
    isSelected: false,
  },
  {
    id: 51,
    value: 10,
    suit: 'spades',
    name: 'queen_of_spades2',
    isSelected: false,
  },
  {
    id: 52,
    value: 10,
    suit: 'spades',
    name: 'king_of_spades2',
    isSelected: false,
  },
]